package com.example.businessstore.service.impl;
import com.example.businessstore.constant.ArtSizeStatus; import com.example.businessstore.dto.request.*; import com.example.businessstore.dto.response.ArtSizeResponse; import com.example.businessstore.entity.ArtSize; import com.example.businessstore.exception.*; import com.example.businessstore.repository.ArtSizeRepository; import com.example.businessstore.service.ArtSizeService; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.util.*;
@Service @RequiredArgsConstructor public class ArtSizeServiceImpl implements ArtSizeService {
 private final ArtSizeRepository repository;
 @Override @Transactional(readOnly=true) public List<ArtSizeResponse> findActive(){return repository.findAllByStatusOrderByNameAsc(ArtSizeStatus.ACTIVE).stream().map(this::response).toList();}
 @Override @Transactional(readOnly=true) public List<ArtSizeResponse> findAllForManagement(){return repository.findAllByOrderByNameAsc().stream().map(this::response).toList();}
 @Override @Transactional public ArtSizeResponse create(CreateArtSizeRequest r){String code=code(r.code()); if(repository.existsByCodeIgnoreCase(code)) throw new AppException(ErrorCode.ART_SIZE_CODE_ALREADY_EXISTS,"Mã khổ tranh này đã tồn tại."); ArtSize size=new ArtSize(); size.setCode(code); size.setName(name(r.name())); setDimensions(size,code,r.widthCm(),r.heightCm()); size.setStatus(ArtSizeStatus.ACTIVE); return response(repository.save(size));}
 @Override @Transactional public ArtSizeResponse update(UUID id, UpdateArtSizeRequest r){ArtSize size=get(id); String code=r.code()==null?size.getCode():code(r.code()); if(r.code()!=null&&repository.existsByCodeIgnoreCaseAndIdNot(code,id)) throw new AppException(ErrorCode.ART_SIZE_CODE_ALREADY_EXISTS,"Mã khổ tranh này đã tồn tại."); size.setCode(code); if(r.name()!=null)size.setName(name(r.name())); if(r.widthCm()!=null||r.heightCm()!=null) setDimensions(size,code,r.widthCm(),r.heightCm()); if(r.status()!=null)size.setStatus(r.status()); return response(size);}
 @Override @Transactional(readOnly=true) public ArtSize requireActive(UUID id){return repository.findByIdAndStatus(id,ArtSizeStatus.ACTIVE).orElseThrow(()->new AppException(ErrorCode.ART_SIZE_NOT_ACTIVE,"Hãy chọn một khổ tranh đang mở bán."));}
 @Override public void validateDimensions(ArtSize s,BigDecimal w,BigDecimal h){if(s.isCustom())return; if(s.getWidthCm()==null||s.getHeightCm()==null||!((same(w,s.getWidthCm())&&same(h,s.getHeightCm()))||(same(w,s.getHeightCm())&&same(h,s.getWidthCm()))))throw new AppException(ErrorCode.ART_SIZE_DIMENSION_MISMATCH,"Kích thước của phiên bản phải khớp với khổ tranh đã chọn.");}
 private void setDimensions(ArtSize s,String c,BigDecimal w,BigDecimal h){if("CUSTOM".equals(c)){s.setWidthCm(null);s.setHeightCm(null);return;} if(w==null||h==null)throw new AppException(ErrorCode.INVALID_ART_SIZE,"Khổ dựng sẵn phải có cả chiều rộng và chiều cao."); s.setWidthCm(w);s.setHeightCm(h);}
 private ArtSize get(UUID id){return repository.findById(id).orElseThrow(()->new AppException(ErrorCode.ART_SIZE_NOT_FOUND,"Không tìm thấy khổ tranh."));} private ArtSizeResponse response(ArtSize s){return new ArtSizeResponse(s.getId(),s.getCode(),s.getName(),s.getWidthCm(),s.getHeightCm(),s.getStatus());} private String code(String v){String c=v.trim().toUpperCase(Locale.ROOT).replaceAll("[^A-Z0-9]+","_").replaceAll("^_+|_+$","");if(c.isBlank())throw new AppException(ErrorCode.INVALID_ART_SIZE,"Mã khổ tranh không hợp lệ.");return c;}private String name(String v){return v.trim().replaceAll("\\s+"," ");}private boolean same(BigDecimal a,BigDecimal b){return a.compareTo(b)==0;}
}
