package com.example.businessstore.exception;

import org.springframework.http.HttpStatus;

public enum ErrorCode {
    INVALID_REQUEST(HttpStatus.BAD_REQUEST, "INVALID_REQUEST"),
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST, "VALIDATION_ERROR"),
    EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT, "EMAIL_ALREADY_EXISTS"),
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND, "RESOURCE_NOT_FOUND"),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED, "INVALID_CREDENTIALS"),
    INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED, "INVALID_REFRESH_TOKEN"),
    INVALID_PASSWORD_RESET_TOKEN(HttpStatus.UNAUTHORIZED, "INVALID_PASSWORD_RESET_TOKEN"),
    GOOGLE_OAUTH_NOT_CONFIGURED(HttpStatus.SERVICE_UNAVAILABLE, "GOOGLE_OAUTH_NOT_CONFIGURED"),
    GOOGLE_AUTHENTICATION_FAILED(HttpStatus.BAD_GATEWAY, "GOOGLE_AUTHENTICATION_FAILED"),
    INVALID_GOOGLE_ID_TOKEN(HttpStatus.UNAUTHORIZED, "INVALID_GOOGLE_ID_TOKEN"),
    EMAIL_DELIVERY_FAILED(HttpStatus.SERVICE_UNAVAILABLE, "EMAIL_DELIVERY_FAILED"),
    CATEGORY_NOT_FOUND(HttpStatus.NOT_FOUND, "CATEGORY_NOT_FOUND"),
    CATEGORY_NAME_ALREADY_EXISTS(HttpStatus.CONFLICT, "CATEGORY_NAME_ALREADY_EXISTS"),
    INVALID_CATEGORY_NAME(HttpStatus.BAD_REQUEST, "INVALID_CATEGORY_NAME"),
    CATEGORY_HAS_PRODUCTS(HttpStatus.CONFLICT, "CATEGORY_HAS_PRODUCTS"),
    PRODUCT_NOT_FOUND(HttpStatus.NOT_FOUND, "PRODUCT_NOT_FOUND"),
    INVALID_PRODUCT_NAME(HttpStatus.BAD_REQUEST, "INVALID_PRODUCT_NAME"),
    INVALID_PRODUCT_CATALOG_FILTER(HttpStatus.BAD_REQUEST, "INVALID_PRODUCT_CATALOG_FILTER"),
    PRODUCT_IMAGE_NOT_FOUND(HttpStatus.NOT_FOUND, "PRODUCT_IMAGE_NOT_FOUND"),
    INVALID_IMAGE_FILE(HttpStatus.BAD_REQUEST, "INVALID_IMAGE_FILE"),
    IMAGE_FILE_TOO_LARGE(HttpStatus.BAD_REQUEST, "IMAGE_FILE_TOO_LARGE"),
    MEDIA_PROVIDER_NOT_CONFIGURED(HttpStatus.SERVICE_UNAVAILABLE, "MEDIA_PROVIDER_NOT_CONFIGURED"),
    MEDIA_UPLOAD_FAILED(HttpStatus.BAD_GATEWAY, "MEDIA_UPLOAD_FAILED"),
    MEDIA_DELETE_FAILED(HttpStatus.BAD_GATEWAY, "MEDIA_DELETE_FAILED"),
    FRAME_NOT_FOUND(HttpStatus.NOT_FOUND, "FRAME_NOT_FOUND"),
    FRAME_NAME_ALREADY_EXISTS(HttpStatus.CONFLICT, "FRAME_NAME_ALREADY_EXISTS"),
    INVALID_FRAME_NAME(HttpStatus.BAD_REQUEST, "INVALID_FRAME_NAME"),
    FRAME_IN_USE(HttpStatus.CONFLICT, "FRAME_IN_USE"),
    PRODUCT_FRAME_OPTION_NOT_FOUND(HttpStatus.NOT_FOUND, "PRODUCT_FRAME_OPTION_NOT_FOUND"),
    PRODUCT_FRAME_OPTION_ALREADY_EXISTS(HttpStatus.CONFLICT, "PRODUCT_FRAME_OPTION_ALREADY_EXISTS"),
    PRODUCT_NOT_AVAILABLE(HttpStatus.CONFLICT, "PRODUCT_NOT_AVAILABLE"),
    PRODUCT_FRAME_OPTION_NOT_AVAILABLE(HttpStatus.CONFLICT, "PRODUCT_FRAME_OPTION_NOT_AVAILABLE"),
    INSUFFICIENT_PRODUCT_STOCK(HttpStatus.CONFLICT, "INSUFFICIENT_PRODUCT_STOCK"),
    CART_ITEM_NOT_FOUND(HttpStatus.NOT_FOUND, "CART_ITEM_NOT_FOUND"),
    CART_EMPTY(HttpStatus.CONFLICT, "CART_EMPTY"),
    ORDER_NOT_FOUND(HttpStatus.NOT_FOUND, "ORDER_NOT_FOUND"),
    INVALID_ORDER_STATUS(HttpStatus.CONFLICT, "INVALID_ORDER_STATUS"),
    ORDER_CANNOT_BE_CANCELLED(HttpStatus.CONFLICT, "ORDER_CANNOT_BE_CANCELLED"),
    ORDER_NOT_PAYABLE(HttpStatus.CONFLICT, "ORDER_NOT_PAYABLE"),
    PAYMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "PAYMENT_NOT_FOUND"),
    PAYMENT_ALREADY_EXISTS(HttpStatus.CONFLICT, "PAYMENT_ALREADY_EXISTS"),
    PAYMENT_METHOD_NOT_SUPPORTED(HttpStatus.BAD_REQUEST, "PAYMENT_METHOD_NOT_SUPPORTED"),
    PAYMENT_CANNOT_BE_COMPLETED(HttpStatus.CONFLICT, "PAYMENT_CANNOT_BE_COMPLETED"),
    COD_PAYMENT_REQUIRED(HttpStatus.CONFLICT, "COD_PAYMENT_REQUIRED"),
    SHIPMENT_CANNOT_BE_CHANGED(HttpStatus.CONFLICT, "SHIPMENT_CANNOT_BE_CHANGED"),
    CUSTOM_ORDER_REQUEST_NOT_FOUND(HttpStatus.NOT_FOUND, "CUSTOM_ORDER_REQUEST_NOT_FOUND"),
    CUSTOM_ORDER_REQUEST_NOT_EDITABLE(HttpStatus.CONFLICT, "CUSTOM_ORDER_REQUEST_NOT_EDITABLE"),
    INVALID_CUSTOM_ORDER_STATUS(HttpStatus.CONFLICT, "INVALID_CUSTOM_ORDER_STATUS"),
    CUSTOM_ORDER_SHIPPING_ADDRESS_REQUIRED(HttpStatus.BAD_REQUEST, "CUSTOM_ORDER_SHIPPING_ADDRESS_REQUIRED"),
    SHIPPING_ADDRESS_NOT_FOUND(HttpStatus.NOT_FOUND, "SHIPPING_ADDRESS_NOT_FOUND"),
    SHIPMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "SHIPMENT_NOT_FOUND"),
    SHIPMENT_NOT_READY(HttpStatus.CONFLICT, "SHIPMENT_NOT_READY"),
    SHIPMENT_ALREADY_EXISTS(HttpStatus.CONFLICT, "SHIPMENT_ALREADY_EXISTS"),
    TRACKING_CODE_ALREADY_EXISTS(HttpStatus.CONFLICT, "TRACKING_CODE_ALREADY_EXISTS"),
    INVALID_SHIPMENT_STATUS(HttpStatus.CONFLICT, "INVALID_SHIPMENT_STATUS"),
    PRODUCT_VARIANT_NOT_FOUND(HttpStatus.NOT_FOUND, "PRODUCT_VARIANT_NOT_FOUND"),
    PRODUCT_VARIANT_REQUIRED(HttpStatus.BAD_REQUEST, "PRODUCT_VARIANT_REQUIRED"),
    PRODUCT_VARIANT_NOT_AVAILABLE(HttpStatus.CONFLICT, "PRODUCT_VARIANT_NOT_AVAILABLE"),
    VARIANT_SKU_ALREADY_EXISTS(HttpStatus.CONFLICT, "VARIANT_SKU_ALREADY_EXISTS"),
    INVALID_FRAME_COMPATIBILITY(HttpStatus.BAD_REQUEST, "INVALID_FRAME_COMPATIBILITY"),
    PROMOTION_NOT_FOUND(HttpStatus.NOT_FOUND, "PROMOTION_NOT_FOUND"),
    PROMOTION_CODE_ALREADY_EXISTS(HttpStatus.CONFLICT, "PROMOTION_CODE_ALREADY_EXISTS"),
    PROMOTION_NOT_ACTIVE(HttpStatus.CONFLICT, "PROMOTION_NOT_ACTIVE"),
    PROMOTION_EXPIRED(HttpStatus.CONFLICT, "PROMOTION_EXPIRED"),
    INVALID_PROMOTION_PERIOD(HttpStatus.BAD_REQUEST, "INVALID_PROMOTION_PERIOD"),
    INVALID_PROMOTION_VALUE(HttpStatus.BAD_REQUEST, "INVALID_PROMOTION_VALUE"),
    PROMOTION_MIN_ORDER_NOT_MET(HttpStatus.CONFLICT, "PROMOTION_MIN_ORDER_NOT_MET"),
    PROMOTION_NOT_APPLICABLE(HttpStatus.CONFLICT, "PROMOTION_NOT_APPLICABLE"),
    PROMOTION_USAGE_LIMIT_REACHED(HttpStatus.CONFLICT, "PROMOTION_USAGE_LIMIT_REACHED"),
    PROMOTION_USER_LIMIT_REACHED(HttpStatus.CONFLICT, "PROMOTION_USER_LIMIT_REACHED"),
    PROMOTION_NOT_EDITABLE(HttpStatus.CONFLICT, "PROMOTION_NOT_EDITABLE"),
    PROMOTION_RESERVATION_EXPIRED(HttpStatus.CONFLICT, "PROMOTION_RESERVATION_EXPIRED"),
    WISHLIST_ITEM_NOT_FOUND(HttpStatus.NOT_FOUND, "WISHLIST_ITEM_NOT_FOUND"),
    NOTIFICATION_NOT_FOUND(HttpStatus.NOT_FOUND, "NOTIFICATION_NOT_FOUND"),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED, "UNAUTHORIZED"),
    FORBIDDEN(HttpStatus.FORBIDDEN, "FORBIDDEN"),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "INTERNAL_ERROR");

    private final HttpStatus httpStatus;
    private final String value;

    ErrorCode(HttpStatus httpStatus, String value) {
        this.httpStatus = httpStatus;
        this.value = value;
    }

    public HttpStatus httpStatus() {
        return httpStatus;
    }

    public String value() {
        return value;
    }
}
