package com.example.businessstore.exception;

import org.springframework.http.HttpStatus;

public enum ErrorCode {
    INVALID_REQUEST(HttpStatus.BAD_REQUEST, "INVALID_REQUEST"),
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST, "VALIDATION_ERROR"),
    EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT, "EMAIL_ALREADY_EXISTS"),
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND, "RESOURCE_NOT_FOUND"),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED, "INVALID_CREDENTIALS"),
    INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED, "INVALID_REFRESH_TOKEN"),
    INVALID_PASSWORD_RESET_TOKEN(HttpStatus.UNAUTHORIZED, "INVALID_PASSWORD_RESET_TOKEN"),
    GOOGLE_OAUTH_NOT_CONFIGURED(HttpStatus.SERVICE_UNAVAILABLE, "GOOGLE_OAUTH_NOT_CONFIGURED"),
    GOOGLE_AUTHENTICATION_FAILED(HttpStatus.BAD_GATEWAY, "GOOGLE_AUTHENTICATION_FAILED"),
    INVALID_GOOGLE_ID_TOKEN(HttpStatus.UNAUTHORIZED, "INVALID_GOOGLE_ID_TOKEN"),
    EMAIL_DELIVERY_FAILED(HttpStatus.SERVICE_UNAVAILABLE, "EMAIL_DELIVERY_FAILED"),
    CATEGORY_NOT_FOUND(HttpStatus.NOT_FOUND, "CATEGORY_NOT_FOUND"),
    CATEGORY_NAME_ALREADY_EXISTS(HttpStatus.CONFLICT, "CATEGORY_NAME_ALREADY_EXISTS"),
    INVALID_CATEGORY_NAME(HttpStatus.BAD_REQUEST, "INVALID_CATEGORY_NAME"),
    CATEGORY_HAS_PRODUCTS(HttpStatus.CONFLICT, "CATEGORY_HAS_PRODUCTS"),
    PRODUCT_NOT_FOUND(HttpStatus.NOT_FOUND, "PRODUCT_NOT_FOUND"),
    INVALID_PRODUCT_NAME(HttpStatus.BAD_REQUEST, "INVALID_PRODUCT_NAME"),
    PRODUCT_IMAGE_NOT_FOUND(HttpStatus.NOT_FOUND, "PRODUCT_IMAGE_NOT_FOUND"),
    INVALID_IMAGE_FILE(HttpStatus.BAD_REQUEST, "INVALID_IMAGE_FILE"),
    IMAGE_FILE_TOO_LARGE(HttpStatus.BAD_REQUEST, "IMAGE_FILE_TOO_LARGE"),
    MEDIA_PROVIDER_NOT_CONFIGURED(HttpStatus.SERVICE_UNAVAILABLE, "MEDIA_PROVIDER_NOT_CONFIGURED"),
    MEDIA_UPLOAD_FAILED(HttpStatus.BAD_GATEWAY, "MEDIA_UPLOAD_FAILED"),
    MEDIA_DELETE_FAILED(HttpStatus.BAD_GATEWAY, "MEDIA_DELETE_FAILED"),
    FRAME_NOT_FOUND(HttpStatus.NOT_FOUND, "FRAME_NOT_FOUND"),
    FRAME_NAME_ALREADY_EXISTS(HttpStatus.CONFLICT, "FRAME_NAME_ALREADY_EXISTS"),
    INVALID_FRAME_NAME(HttpStatus.BAD_REQUEST, "INVALID_FRAME_NAME"),
    FRAME_IN_USE(HttpStatus.CONFLICT, "FRAME_IN_USE"),
    PRODUCT_FRAME_OPTION_NOT_FOUND(HttpStatus.NOT_FOUND, "PRODUCT_FRAME_OPTION_NOT_FOUND"),
    PRODUCT_FRAME_OPTION_ALREADY_EXISTS(HttpStatus.CONFLICT, "PRODUCT_FRAME_OPTION_ALREADY_EXISTS"),
    PRODUCT_NOT_AVAILABLE(HttpStatus.CONFLICT, "PRODUCT_NOT_AVAILABLE"),
    PRODUCT_FRAME_OPTION_NOT_AVAILABLE(HttpStatus.CONFLICT, "PRODUCT_FRAME_OPTION_NOT_AVAILABLE"),
    INSUFFICIENT_PRODUCT_STOCK(HttpStatus.CONFLICT, "INSUFFICIENT_PRODUCT_STOCK"),
    CART_ITEM_NOT_FOUND(HttpStatus.NOT_FOUND, "CART_ITEM_NOT_FOUND"),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED, "UNAUTHORIZED"),
    FORBIDDEN(HttpStatus.FORBIDDEN, "FORBIDDEN"),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "INTERNAL_ERROR");

    private final HttpStatus httpStatus;
    private final String value;

    ErrorCode(HttpStatus httpStatus, String value) {
        this.httpStatus = httpStatus;
        this.value = value;
    }

    public HttpStatus httpStatus() {
        return httpStatus;
    }

    public String value() {
        return value;
    }
}
