import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { apiRequest } from '../api/http'

type Category = { id: string; name: string }
type ProductStatus = 'DRAFT' | 'PUBLISHED' | 'ARCHIVED'
type Product = { id: string; categoryId: string; categoryName: string; name: string; slug: string; description: string | null; price: number; widthCm: number | null; heightCm: number | null; stockQuantity: number; status: ProductStatus }
type Page<T> = { items: T[]; page: number; size: number; totalElements: number; totalPages: number; hasNext: boolean }
const money = new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 })
const errorText = (error: unknown) => error instanceof Error ? error.message : 'Đã có lỗi xảy ra.'

function Pagination({ data, onPage }: { data: Page<unknown> | null; onPage: (page: number) => void }) { if (!data || data.totalPages <= 1) return null; return <div className="pagination"><button disabled={data.page <= 1} onClick={() => onPage(data.page - 1)}>← Trước</button><span>Trang {data.page}/{data.totalPages} · {data.totalElements} sản phẩm</span><button disabled={!data.hasNext} onClick={() => onPage(data.page + 1)}>Sau →</button></div> }

export function ProductsSearchPage() {
  const navigate = useNavigate()
  const [data, setData] = useState<Page<Product> | null>(null)
  const [categories, setCategories] = useState<Category[]>([])
  const [editing, setEditing] = useState<Product | null | undefined>(undefined)
  const [page, setPage] = useState(1)
  const [filters, setFilters] = useState({ name: '', categoryId: '', status: '', stockLevel: '' })
  const [draft, setDraft] = useState(filters)
  const [message, setMessage] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const query = useMemo(() => { const value = new URLSearchParams({ page: String(page), size: '12' }); Object.entries(filters).forEach(([key, item]) => { if (item) value.set(key, item) }); return value.toString() }, [filters, page])
  async function load() { setLoading(true); try { const [products, groups] = await Promise.all([apiRequest<Page<Product>>(`/products/management?${query}`), apiRequest<Category[]>('/categories')]); setData(products); setCategories(groups) } catch (error) { setMessage(errorText(error)) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [query])
  function submit(event: FormEvent) { event.preventDefault(); setPage(1); setFilters(draft) }
  function reset() { const empty = { name: '', categoryId: '', status: '', stockLevel: '' }; setDraft(empty); setFilters(empty); setPage(1) }
  async function remove(product: Product) { if (!window.confirm(`Xóa sản phẩm “${product.name}”? Ảnh và variants cũng sẽ bị xóa.`)) return; try { await apiRequest<void>(`/products/${product.id}`, { method: 'DELETE' }); setMessage('Đã xóa sản phẩm.'); void load() } catch (error) { setMessage(errorText(error)) } }
  return <><header className="catalog-header"><div><p className="eyebrow">CATALOG</p><h2>Sản phẩm</h2><p>Tìm theo tên, danh mục, trạng thái xuất bản và mức tồn kho.</p></div><button className="primary-button compact" onClick={() => setEditing(null)}>+ Thêm sản phẩm</button></header>{message && <p className="catalog-message">{message}</p>}<section className="catalog-panel"><form className="operations-filters operations-filters--products" onSubmit={submit}><label>Tên sản phẩm<input value={draft.name} placeholder="Nhập tên sản phẩm" onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label>Danh mục<select value={draft.categoryId} onChange={(event) => setDraft({ ...draft, categoryId: event.target.value })}><option value="">Tất cả</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Trạng thái<select value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value })}><option value="">Tất cả</option>{(['DRAFT', 'PUBLISHED', 'ARCHIVED'] as ProductStatus[]).map((item) => <option key={item}>{item}</option>)}</select></label><label>Tồn kho<select value={draft.stockLevel} onChange={(event) => setDraft({ ...draft, stockLevel: event.target.value })}><option value="">Tất cả</option><option value="OUT_OF_STOCK">Hết hàng (0)</option><option value="LOW_STOCK">Sắp hết (1–5)</option><option value="IN_STOCK">Còn hàng (≥6)</option></select></label><button className="primary-button compact">Tìm kiếm</button><button type="button" className="filter-reset" onClick={reset}>Xóa lọc</button></form>{loading ? <p className="table-loading">Đang tải sản phẩm…</p> : <><table className="data-table"><thead><tr><th>Sản phẩm</th><th>Danh mục</th><th>Giá</th><th>Tồn kho</th><th>Trạng thái</th><th /></tr></thead><tbody>{data?.items.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.slug}</small></td><td>{item.categoryName}</td><td>{money.format(item.price)}</td><td>{item.stockQuantity}</td><td><span className={`status status--${item.status.toLowerCase()}`}>{item.status}</span></td><td className="table-actions"><button onClick={() => navigate(`/admin/products/${item.id}`)}>Chi tiết</button><button onClick={() => setEditing(item)}>Sửa</button><button className="danger-text" onClick={() => void remove(item)}>Xóa</button></td></tr>)}</tbody></table>{data?.items.length === 0 && <p className="empty-state">Không tìm thấy sản phẩm phù hợp.</p>}<Pagination data={data} onPage={setPage} /></>}</section>{editing !== undefined && <ProductForm item={editing} categories={categories} onClose={() => setEditing(undefined)} onSaved={() => { setEditing(undefined); setMessage('Đã lưu sản phẩm.'); void load() }} />}</>
}

function ProductForm({ item, categories, onClose, onSaved }: { item: Product | null; categories: Category[]; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState({ categoryId: item?.categoryId ?? '', name: item?.name ?? '', description: item?.description ?? '', price: String(item?.price ?? ''), widthCm: item?.widthCm == null ? '' : String(item.widthCm), heightCm: item?.heightCm == null ? '' : String(item.heightCm), stockQuantity: String(item?.stockQuantity ?? 0), status: item?.status ?? 'DRAFT' })
  const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false)
  const change = (key: keyof typeof form, value: string) => setForm({ ...form, [key]: value })
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { await apiRequest<Product>(item ? `/products/${item.id}` : '/products', { method: item ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, price: Number(form.price), widthCm: form.widthCm ? Number(form.widthCm) : null, heightCm: form.heightCm ? Number(form.heightCm) : null, stockQuantity: Number(form.stockQuantity) }) }); onSaved() } catch (cause) { setError(errorText(cause)) } finally { setBusy(false) } }
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label={item ? 'Sửa sản phẩm' : 'Thêm sản phẩm'}><header><h3>{item ? 'Sửa sản phẩm' : 'Thêm sản phẩm'}</h3><button type="button" className="icon-button" onClick={onClose}>×</button></header><form className="admin-form" onSubmit={(event) => void submit(event)}><div className="form-grid"><label>Danh mục<select value={form.categoryId} onChange={(event) => change('categoryId', event.target.value)} required><option value="">Chọn danh mục</option>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label>Tên sản phẩm<input value={form.name} onChange={(event) => change('name', event.target.value)} required /></label><label>Giá gốc<input type="number" min="1" step="1000" value={form.price} onChange={(event) => change('price', event.target.value)} required /></label><label>Tồn kho<input type="number" min="0" value={form.stockQuantity} onChange={(event) => change('stockQuantity', event.target.value)} required /></label><label>Rộng (cm)<input type="number" min="0.01" step="0.01" value={form.widthCm} onChange={(event) => change('widthCm', event.target.value)} /></label><label>Cao (cm)<input type="number" min="0.01" step="0.01" value={form.heightCm} onChange={(event) => change('heightCm', event.target.value)} /></label><label>Trạng thái<select value={form.status} onChange={(event) => change('status', event.target.value)}><option value="DRAFT">DRAFT</option><option value="PUBLISHED">PUBLISHED</option><option value="ARCHIVED">ARCHIVED</option></select></label></div><label>Mô tả<textarea rows={4} value={form.description} onChange={(event) => change('description', event.target.value)} /></label>{error && <p className="form-error">{error}</p>}<footer><button type="button" className="ghost-button" onClick={onClose}>Hủy</button><button className="primary-button compact" disabled={busy}>{busy ? 'Đang lưu…' : 'Lưu sản phẩm'}</button></footer></form></section></div>
}
